replicaCount: 1

image:
  repository: louthier/playlist-service
  pullPolicy: Always
  tag: "latest"

env:
  "ASPNETCORE_ENVIRONMENT": Production""
  "DB_CONNECTION_STRING": ""
  "KEYCLOAK_ISSUER": ""
  "KEYCLOAK_RSA_PUBLIC_KEY": ""
  "RABBITMQ_HOST": ""
  "RABBITMQ_VIRTUAL_HOST": ""
  "RABBITMQ_PASSWORD": ""
  "RABBITMQ_USERNAME": ""
  "MONGODB_CONNECTION_STRING": ""
  "MONGODB_DATABASE_NAME": ""
  "MONGODB_COLLECTION_NAME": ""
  "OPEN_TELEMETRY_COLLECTOR_URL": ""
  "DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE": ""

imagePullSecrets:
  - name: regcred
  
service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

serviceAccount:
  create: false